### ISSUE TITLE
Keep header icon even when step is completed

### ISSUE THREAD

**Issue by pj-alvarado10** [DonAdam2/react-dynamic-stepper#1]
Hi!!
My question is exactly the title of the issue:

How can I keep th header icon even when step is completed?

For example, I have:

```
 {
          header: {
            label: t('title-step-1'),
            indicator: <AddDocumentsIcon />
          },
          content: <div>First step content</div>,
          isError: false,
          isWarning: false,
          isComplete: true,
        },
```

I want that the step hast the icon <AddDocumentsIcon /> even when isComplete is true (not the checked icon).

Thank you.

**Comment by DonAdam2** [comment]
Added `isKeepIndicatorOnComplete` in the header of each step which is responsible for showing the indicator if a step is completed

**Comment by pj-alvarado10** [comment]
Thank you so much for your help and your speed!!
