### ISSUE TITLE
Custom palette to disabled color step

### ISSUE THREAD

**Issue by pj-alvarado10** [DonAdam2/react-dynamic-stepper#2]
Hi!
I want a question. I know that the palette is customizable, I have this:

```
  pallet={{
                    default: '#2ABCC7',
                    warning: '#FFC720',
                    danger: '#D7263D',
                    success: '#2ABCC7',
               }}
```

But I need to custom disabled background color in `.AIEdAYEy `class

```
background-color: #e3e8ec;
border: 1px solid #e3e8ec;

```
to 

```
background-color: #F1F5F9;
border: 1px solid #F1F5F9;
```

I put `!important` but then the another palette (default, warning, complete, danger) is replaced too. Then I need know another way to custom this color in background and in the connector. Thank you.

**Comment by DonAdam2** [comment]
Update the pallet object to accept `disabled` key which will update the disabled color of each step and connector:

```
pallet = {
        default: '#627c90',
        warning: '#f1c40f',
        danger: '#e95a4b',
        success: '#4caf50',
        disabled: '#e3e8ec',
      },
```
