### ISSUE TITLE
Custom next label based on current step

### ISSUE THREAD

**Issue by pj-alvarado10** [DonAdam2/react-dynamic-stepper#4]
Hi again!
Thank you for your help!

This time, I need to change the label of the next button about a current step, similar to the default label ("Continue to step <next_step>").

I imagine two ways to do it. 

One is the stepper has a similar function to onClickHandler (Invoked when the next button of the current step is clicked), but when the prev button of the current step is clicked,

The second way is if the stepper has the way to know the active step (a variable or something) and I can call this variable and change the label of next button according the active step.

Maybe there is another way easier but I dont find that in the documentation.

Thank you!! 
And sorry for the inconvenience!

**Comment by DonAdam2** [comment]
Hi, 

I can add `isAppendStepNumber` to the footerData:

```
<Stepper
        steps={steps}
        footerData={{
          isAppendStepNumber: true,
          prevBtnLabel: 'Prev',
          prevBtnClassName: 'prev-button',
          nextBtnLabel: 'Next',
          nextBtnClassName: 'next-button',
          submitBtnLabel: 'Send',
          submitBtnClassName: 'submit-button',
          submitHandler: submitStepper,
        }}
      />
```

Which will return "Next 3" and "Prev 1" if the current step is 2

**Comment by pj-alvarado10** [comment]
> Hi,
> 
> I can add `isAppendStepNumber` to the footerData:
> 
> ```
> <Stepper
>         steps={steps}
>         footerData={{
>           isAppendStepNumber: true,
>           prevBtnLabel: 'Prev',
>           prevBtnClassName: 'prev-button',
>           nextBtnLabel: 'Next',
>           nextBtnClassName: 'next-button',
>           submitBtnLabel: 'Send',
>           submitBtnClassName: 'submit-button',
>           submitHandler: submitStepper,
>         }}
>       />
> ```
> 
> Which will return "Next 3" and "Prev 1" if the current step is 2

Thank you for your very fast answer!! 

I understand, but for example the nextButtonLabel need to be more customizable. For example:

Next button in step 1: "Now register your data!! →"
Next button in step 2: "Go to upload your files →"

Is it possible? Or Do I use the text "Next" and we avoid complexities?

**Comment by DonAdam2** [comment]
You need to pass different label for each step, if this is the case, I can update each step to accept **footer** object:

```
{
        header: {
          label: 'Step 2',
          indicator: <SignersIcon />,
          isKeepIndicatorOnComplete: true,
        },
        content: (
          <div>
            <label>
              <input
                type="checkbox"
                checked={acceptSecondTerms.checked}
                onChange={secondTermsHandler}
              />{' '}
              Accept second terms and conditions
            </label>
          </div>
        ),
        onClickHandler: () => secondStepAsyncFunc(),
        isLoading: isSecondStepLoading,
        isError: !acceptSecondTerms.checked && acceptSecondTerms.touched,
        isComplete: acceptSecondTerms.checked,
        footer: {
          nextButtonLabel: 'Custom label',
          prevButtonLabel: 'Custom label',
      }
},
```

**Comment by pj-alvarado10** [comment]
> You need to pass different label for each step, if this is the case, I can update each step to accept **footer** object:
> 
> ```
> {
>         header: {
>           label: 'Step 2',
>           indicator: <SignersIcon />,
>           isKeepIndicatorOnComplete: true,
>         },
>         content: (
>           <div>
>             <label>
>               <input
>                 type="checkbox"
>                 checked={acceptSecondTerms.checked}
>                 onChange={secondTermsHandler}
>               />{' '}
>               Accept second terms and conditions
>             </label>
>           </div>
>         ),
>         onClickHandler: () => secondStepAsyncFunc(),
>         isLoading: isSecondStepLoading,
>         isError: !acceptSecondTerms.checked && acceptSecondTerms.touched,
>         isComplete: acceptSecondTerms.checked,
>         footer: {
>           nextButtonLabel: 'Custom label',
>           prevButtonLabel: 'Custom label',
>       }
> },
> ```

This could be great!! And useful! Really, thank you!!

**Comment by DonAdam2** [comment]
Done

**Comment by pj-alvarado10** [comment]
Thank you so much!! I will update the version!!
